### ISSUE TITLE
大佬  我想用这个驱动阿里ct2000（armbian系统）的led灯  可行吗？

### ISSUE THREAD

**Issue by Jack-bin183** [7Ji/YAopenvfD#1]

**Comment by 7Ji** [comment]
https://github.com/7Ji/YAopenvfD#yet-another-openvfd-daemon

> This project is aimed at providing **distro-independent** single-binary feature-equivalent experience to the official OpenVFDService + service.openvfd Kodi addon combination.

本项目是 **无关发行版** 的 OpenVFD 的守护进程

至于设备，每个盒子的VFD显示配列不同，我没有你的盒子

折腾盒子是否能用YAopenvfD，思路是：首先找出openvfd内核驱动的正确参数，然后确保openvfd项目自己的OpenVFDService能跑起来显示时间，或者YAopenvfD测试也行，然后停用OpenVFDService，用YAopenvfD声明你喜欢的显示组合
