### ISSUE TITLE
Disabling usb apps setup sd hdmi cvbs leds

### ISSUE THREAD

**Issue by SanteriSepp** [7Ji/YAopenvfD#2]
Hi, is it possible to disable usb apps setup sd hdmi cvbs leds on display?
I've got temp displaying fine, but all of the accessory leds are on.

Thanks!

**Comment by 7Ji** [comment]
Did you use ophub/amlogic-s9xxx-armbian 's way to init the openvfd driver? In that init script there's a command that will echo led names to `/sys/class/led/openvfd/led_on`, which forces those leds to turn on, and can't be turned off by user space programs, in this case yaopenvfd.

For yaopenvfd to manage those leds, and turn them on and off on events, nothing should he written to `/sys/.../led_on`

An example script to correctly run yaopenvfd as a daemon is available at https://aur.archlinux.org/packages/yaopenvfd . You should use its systemd.service, and don't use armbian-openvfd or whatever script that comes with your distro

**Comment by SanteriSepp** [comment]
That makes sense, all working great now! Thanks for the awesome project!
