### ISSUE TITLE
你好，请问我该如何在armbian系统上使用YAopenvfD项目

### ISSUE THREAD

**Issue by wanjixs** [7Ji/YAopenvfD#3]
你好，请问我该如何在armbian系统上使用YAopenvfD项目，
我使用：
git clone https://github.com/7Ji/YAopenvfD
cd YAopenvfD
make
进行构建
再运行 ./YAopenvfD 0:date:24h
显示：reporter_prepare:137: Initialized collector for reporter type 6(date) duration 0
但是我的hk1 box 机顶盒仍然黑屏，没有显示任何字符串

大佬能说说如何在armbian系统上使用YAopenvfD项目吗，也可付费咨询

**Comment by wanjixs** [comment]
希望大佬能稍微解答一下怎么在安装armbian系统的hk1 box里运行YAopenvfD，今天自己折腾摸索了一天都没解决，感谢大佬，

**Comment by AZhe2333** [comment]
先执行armbian-openvfd，再用./YAopenvfD 试试🤔

需要先加载模块，才能控制

**Comment by wanjixs** [comment]
你好，大佬，执行armbian-openvfd，选择15，hk1 box 成功显示时间。
再执行./YAopenvfD 0:temp:0  或者./YAopenvfD 5:temp:0 3:string:-a- 5:date:24h 5:date:12h 3:string:mvm等等，hk1屏幕成功显示对应内容约0.2秒又显示回默认的时间，请问能付费帮忙远程调试一下吗，

我还有一个2020年版本的armbian，并没有集armbian-openvfd项目，也没有openvfd项目，能帮忙在这个2020版本的armbian版本上运行你的YAopenvfD项目吗，我这边可以给280元报酬，可以的话我把这个armbian镜像文件发给你
________________________________
发件人: ***@***.*** ***@***.***> 代表 AZhe2333 ***@***.***>
发送时间: 2024年4月2日 03:02
收件人: 7Ji/YAopenvfD ***@***.***>
抄送: wanjixs ***@***.***>; Author ***@***.***>
主题: Re: [7Ji/YAopenvfD] 你好，请问我该如何在armbian系统上使用YAopenvfD项目 (Issue #3)


先执行armbian-openvfd，再用./YAopenvfD 试试🤔

需要先加载模块，才能控制

**Comment by 7Ji** [comment]
运行逻辑参考 https://aur.archlinux.org/packages/YAopenvfD

任何系统，不限于Arch，都需要把openvfd的配置放在`/etc/conf.d/YAopenvfD` （上引YAopenvfD.conf），把上引`YAopenvfD.service`放到系统的`/etc/systemd/system`文件夹里，再`systemctl enable --now YAopenvfD.service`，这个service会在以正确参数加载`openvfd`内核模块（但不显示任何内容）以后再把`yaopenvfd`跑起来显示设定内容

不要，不要混用`armbian-openvfd`

不要单独运行`yaopenvfd`可执行程序，这个程序只负责每帧向内核通告如何显示下一帧，在不加载`openvfd`内核模块的情况下，它自己是没法完成显示的
